#!/bin/bash

SCRIPT_DIR=$PWD
WATCH_DIR=$1
cd ${WATCH_DIR}
watchman-wait . --pattern '*.storyboard' --max-events 0 |
while read -r FILENAME
do
	read
	STORYBOARD="$SCRIPT_DIR/${WATCH_DIR}${FILENAME}"
	SWIFT_DIR="$SCRIPT_DIR/${WATCH_DIR}"
	${SCRIPT_DIR}/ComponentCreator $STORYBOARD $SWIFT_DIR
	read
done
